In [47]:
import pandas as pd

In [48]:
# loading the scraped data
# and checking it out

df = pd.read_csv('../scraping/allmovies-2k.csv')
df

,Movie Name,Genres,Time,Rating,Top Cast
0,Venom: The Last Dance\n(2024),"Action, Science Fiction, Adventure, Thriller",1h 49m,68,Tom HardyEddie Brock / Venom Chiwetel Eji...
1,Moana 2\n(2024),"Animation, Adventure, Family, Comedy",1h 40m,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...
2,Elevation\n(2024),"Action, Science Fiction, Thriller",1h 31m,63,Anthony MackieWill Morena BaccarinNina ...
3,Absolution\n(2024),"Action, Crime, Thriller",1h 52m,59,Liam NeesonThug Ron PerlmanCharlie Conner...
4,Red One\n(2024),"Action, Fantasy, Comedy",2h 4m,70,Dwayne JohnsonCallum Drift Chris EvansJac...
...,...,...,...,...,...
1969,Killer Heat\n(2024),"Crime, Drama, Romance",1h 37m,58,Richard MaddenLeonides / Elias Vardakis J...
1970,Emmanuelle: The Joys of a Woman\n(1975),"Drama, Romance",1h 24m,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...
1971,Peter Pan\n(1953),"Animation, Family, Adventure, Fantasy",1h 17m,72,Bobby DriscollPeter Pan (voice) Kathryn B...
1972,Casper\n(1995),"Fantasy, Comedy, Family",1h 40m,63,Malachi PearsonCasper (voice) Christina R...
1973,Licence to Kill\n(1989),"Adventure, Action, Thriller",2h 13m,64,Timothy DaltonJames Bond Carey LowellPam ...

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Movie Name  1974 non-null   object
 1   Genres      1973 non-null   object
 2   Time        1974 non-null   object
 3   Rating      1974 non-null   int64
 4   Top Cast    1974 non-null   object
dtypes: int64(1), object(4)
memory usage: 77.2+ KB

In [50]:
# removing '\r\n' from movie name
df['Movie Name'] = df['Movie Name'].str.replace('\n', ' ')
df

,Movie Name,Genres,Time,Rating,Top Cast
0,Venom: The Last Dance (2024),"Action, Science Fiction, Adventure, Thriller",1h 49m,68,Tom HardyEddie Brock / Venom Chiwetel Eji...
1,Moana 2 (2024),"Animation, Adventure, Family, Comedy",1h 40m,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...
2,Elevation (2024),"Action, Science Fiction, Thriller",1h 31m,63,Anthony MackieWill Morena BaccarinNina ...
3,Absolution (2024),"Action, Crime, Thriller",1h 52m,59,Liam NeesonThug Ron PerlmanCharlie Conner...
4,Red One (2024),"Action, Fantasy, Comedy",2h 4m,70,Dwayne JohnsonCallum Drift Chris EvansJac...
...,...,...,...,...,...
1969,Killer Heat (2024),"Crime, Drama, Romance",1h 37m,58,Richard MaddenLeonides / Elias Vardakis J...
1970,Emmanuelle: The Joys of a Woman (1975),"Drama, Romance",1h 24m,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...
1971,Peter Pan (1953),"Animation, Family, Adventure, Fantasy",1h 17m,72,Bobby DriscollPeter Pan (voice) Kathryn B...
1972,Casper (1995),"Fantasy, Comedy, Family",1h 40m,63,Malachi PearsonCasper (voice) Christina R...
1973,Licence to Kill (1989),"Adventure, Action, Thriller",2h 13m,64,Timothy DaltonJames Bond Carey LowellPam ...

In [51]:
# dropping the movie that has any hindi letter

def is_english(string):
    # for each character in string
    # check if it can exist in ascii (0 to 255)
    # we confirmed that hindi letters are way beyond 255
    for c in string:
        if ord(c) > 255:
            return False
    return True


# this mask has True for english movies and False for hindi movies
english_mask = df['Movie Name'].apply(is_english)

print("Before applying mask", df.shape)
df = df[english_mask]
print("After applying mask", df.shape)

df

Before applying mask (1974, 5)
After applying mask (1967, 5)

,Movie Name,Genres,Time,Rating,Top Cast
0,Venom: The Last Dance (2024),"Action, Science Fiction, Adventure, Thriller",1h 49m,68,Tom HardyEddie Brock / Venom Chiwetel Eji...
1,Moana 2 (2024),"Animation, Adventure, Family, Comedy",1h 40m,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...
2,Elevation (2024),"Action, Science Fiction, Thriller",1h 31m,63,Anthony MackieWill Morena BaccarinNina ...
3,Absolution (2024),"Action, Crime, Thriller",1h 52m,59,Liam NeesonThug Ron PerlmanCharlie Conner...
4,Red One (2024),"Action, Fantasy, Comedy",2h 4m,70,Dwayne JohnsonCallum Drift Chris EvansJac...
...,...,...,...,...,...
1969,Killer Heat (2024),"Crime, Drama, Romance",1h 37m,58,Richard MaddenLeonides / Elias Vardakis J...
1970,Emmanuelle: The Joys of a Woman (1975),"Drama, Romance",1h 24m,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...
1971,Peter Pan (1953),"Animation, Family, Adventure, Fantasy",1h 17m,72,Bobby DriscollPeter Pan (voice) Kathryn B...
1972,Casper (1995),"Fantasy, Comedy, Family",1h 40m,63,Malachi PearsonCasper (voice) Christina R...
1973,Licence to Kill (1989),"Adventure, Action, Thriller",2h 13m,64,Timothy DaltonJames Bond Carey LowellPam ...

In [52]:
# we just droppepd some rows
# reset the index, so its easier to work with
df = df.reset_index(drop=True)

In [53]:
# converting time to minutes

def convert(time_str):
    # time_str could be '1h 10m' or '20m' or '1h'
    time_str = time_str.replace(' ', '')
    time_str = time_str.replace('m', '')
    # now time_str could be '1h10' or '20' or '1h'

    time_split = time_str.split('h')
    hours = 0
    minutes = 0

    if 'h' in time_str:
        # if 'h' is in time_str
        # time_split[0] will be hours
        # time_split[1] will be minutes
        # but time_split[1] could be empty
        hours = int(time_split[0])
        if time_split[1] != '':
            minutes = int(time_split[1])
    else:
        # if 'h' is not in time_str
        # time_split[0] will be minutes
        minutes = int(time_split[0])
    
    return hours * 60 + minutes


df['Time'] = df['Time'].apply(convert)
df

,Movie Name,Genres,Time,Rating,Top Cast
0,Venom: The Last Dance (2024),"Action, Science Fiction, Adventure, Thriller",109,68,Tom HardyEddie Brock / Venom Chiwetel Eji...
1,Moana 2 (2024),"Animation, Adventure, Family, Comedy",100,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...
2,Elevation (2024),"Action, Science Fiction, Thriller",91,63,Anthony MackieWill Morena BaccarinNina ...
3,Absolution (2024),"Action, Crime, Thriller",112,59,Liam NeesonThug Ron PerlmanCharlie Conner...
4,Red One (2024),"Action, Fantasy, Comedy",124,70,Dwayne JohnsonCallum Drift Chris EvansJac...
...,...,...,...,...,...
1962,Killer Heat (2024),"Crime, Drama, Romance",97,58,Richard MaddenLeonides / Elias Vardakis J...
1963,Emmanuelle: The Joys of a Woman (1975),"Drama, Romance",84,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...
1964,Peter Pan (1953),"Animation, Family, Adventure, Fantasy",77,72,Bobby DriscollPeter Pan (voice) Kathryn B...
1965,Casper (1995),"Fantasy, Comedy, Family",100,63,Malachi PearsonCasper (voice) Christina R...
1966,Licence to Kill (1989),"Adventure, Action, Thriller",133,64,Timothy DaltonJames Bond Carey LowellPam ...

In [54]:
# getting unique genres

unique_genres = []

for genres in df['Genres']:
    if isinstance(genres, str): # Checking if it's a string
        # genres is of form 'Action,Drama,Romance'
        genres = genres.split(',')
        # genres is now ['Action', 'Drama', 'Romance']
        for g in genres:
            # g is 'Action' or '\xa0Action'
            g = g.replace('\xa0', '')
            # g is now 'Action'
            # it is unique if it is not in the list
            if g not in unique_genres:
                unique_genres.append(g)

unique_genres

['Action',
 'Science Fiction',
 'Adventure',
 'Thriller',
 'Animation',
 'Family',
 'Comedy',
 'Crime',
 'Fantasy',
 'Mystery',
 'Drama',
 'Romance',
 'Horror',
 'History',
 'War',
 'TV Movie',
 'Music',
 'Documentary',
 'Western']

In [55]:
genres_df = df['Genres'].to_frame()

for genre in unique_genres:
    genres_df.insert(0, genre, 0)

genres_df

,Western,Documentary,Music,TV Movie,War,History,Horror,Romance,Drama,Mystery,Fantasy,Crime,Comedy,Family,Animation,Thriller,Adventure,Science Fiction,Action,Genres
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Action, Science Fiction, Adventure, Thriller"
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Animation, Adventure, Family, Comedy"
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Action, Science Fiction, Thriller"
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Action, Crime, Thriller"
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Action, Fantasy, Comedy"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Crime, Drama, Romance"
1963,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Drama, Romance"
1964,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Animation, Family, Adventure, Fantasy"
1965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Fantasy, Comedy, Family"
1966,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Adventure, Action, Thriller"

In [56]:
# filling the genres df with proper values
# then dropping the old column

for idx in range(len(genres_df)):
    genres = genres_df['Genres'].iloc[idx]
    if isinstance(genres, str): # Check if it's a string
        # genres is of form "Action,Drama,Romance"
        genres = genres.split(",")

        for genre in genres:
            genre = genre.strip()
            genres_df.at[idx, genre] = 1

genres_df = genres_df.drop(columns=['Genres'])
genres_df

,Western,Documentary,Music,TV Movie,War,History,Horror,Romance,Drama,Mystery,Fantasy,Crime,Comedy,Family,Animation,Thriller,Adventure,Science Fiction,Action
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1
1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1
3,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
4,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0
1963,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0
1964,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,0
1965,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0
1966,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1

In [57]:
# merging the one hot encoded genres with the original dataframe

df = pd.concat([df, genres_df], axis=1)
df = df.drop(columns=['Genres'])
df

,Movie Name,Time,Rating,Top Cast,Western,Documentary,Music,TV Movie,War,History,...,Mystery,Fantasy,Crime,Comedy,Family,Animation,Thriller,Adventure,Science Fiction,Action
0,Venom: The Last Dance (2024),109,68,Tom HardyEddie Brock / Venom Chiwetel Eji...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
1,Moana 2 (2024),100,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
2,Elevation (2024),91,63,Anthony MackieWill Morena BaccarinNina ...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1
3,Absolution (2024),112,59,Liam NeesonThug Ron PerlmanCharlie Conner...,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,1
4,Red One (2024),124,70,Dwayne JohnsonCallum Drift Chris EvansJac...,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Killer Heat (2024),97,58,Richard MaddenLeonides / Elias Vardakis J...,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1963,Emmanuelle: The Joys of a Woman (1975),84,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1964,Peter Pan (1953),77,72,Bobby DriscollPeter Pan (voice) Kathryn B...,0,0,0,0,0,0,...,0,1,0,0,1,1,0,1,0,0
1965,Casper (1995),100,63,Malachi PearsonCasper (voice) Christina R...,0,0,0,0,0,0,...,0,1,0,1,1,0,0,0,0,0
1966,Licence to Kill (1989),133,64,Timothy DaltonJames Bond Carey LowellPam ...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1

In [58]:
print('df shape:', df.shape)
print('df columns:', df.columns)

df.to_csv("cleaned-movies-2k.csv", index=False)

df shape: (1967, 23)
df columns: Index(['Movie Name', 'Time', 'Rating', 'Top Cast', 'Western', 'Documentary',
       'Music', 'TV Movie', 'War', 'History', 'Horror', 'Romance', 'Drama',
       'Mystery', 'Fantasy', 'Crime', 'Comedy', 'Family', 'Animation',
       'Thriller', 'Adventure', 'Science Fiction', 'Action'],
      dtype='object')

In [59]:
import pandas as pd
import re

In [60]:
# Loading dataset
movies_df = pd.read_csv('cleaned-movies-2k.csv')

# Taking only 'Top Cast' column in different dataframe
top_cast_df = movies_df[['Top Cast']].copy()

In [61]:
# Function to keep only English names
def eng_top_cast(cast) :
    # Removes Hindi charac whose unicode is (u0900 to u097F)
    only_eng_name = re.sub(r'[\u0900-\u097F]+', '', cast)
    # Remove extra spaces that may result
    # only_eng_name = re.sub(r"\s+", " ", only_eng_name)
    # only_eng_name = only_eng_name.strip()            # No need for removing extra spaces , it seperates different characters/actors
    # returning 
    return only_eng_name

In [62]:
# Applying function to 'Top Cast' column
top_cast_df['Top Cast'] = top_cast_df['Top Cast'].apply(eng_top_cast)

# Saving the new dataset to a CSV file
top_cast_df.to_csv('cleaned_top_cast-2k.csv', index=False)

# Printing new dataset
top_cast_df

                                               Top Cast
0     Tom HardyEddie Brock / Venom      Chiwetel Eji...
1     Auliʻi CravalhoMoana (voice)      Dwayne Johns...
2     Anthony MackieWill      Morena BaccarinNina   ...
3     Liam NeesonThug      Ron PerlmanCharlie Conner...
4     Dwayne JohnsonCallum Drift      Chris EvansJac...
...                                                 ...
1962  Richard MaddenLeonides / Elias Vardakis      J...
1963  Sylvia KristelEmmanuelle      Umberto OrsiniJe...
1964  Bobby DriscollPeter Pan (voice)      Kathryn B...
1965  Malachi PearsonCasper (voice)      Christina R...
1966  Timothy DaltonJames Bond      Carey LowellPam ...

[1967 rows x 1 columns]

In [63]:
# merging only eng names top_cast_df with the original dataframe

df = df.drop(columns=['Top Cast'])
df = pd.concat([df, top_cast_df], axis=1)
df

,Movie Name,Time,Rating,Western,Documentary,Music,TV Movie,War,History,Horror,...,Fantasy,Crime,Comedy,Family,Animation,Thriller,Adventure,Science Fiction,Action,Top Cast
0,Venom: The Last Dance (2024),109,68,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,Tom HardyEddie Brock / Venom Chiwetel Eji...
1,Moana 2 (2024),100,70,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,0,Auliʻi CravalhoMoana (voice) Dwayne Johns...
2,Elevation (2024),91,63,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,Anthony MackieWill Morena BaccarinNina ...
3,Absolution (2024),112,59,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,Liam NeesonThug Ron PerlmanCharlie Conner...
4,Red One (2024),124,70,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,Dwayne JohnsonCallum Drift Chris EvansJac...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Killer Heat (2024),97,58,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Richard MaddenLeonides / Elias Vardakis J...
1963,Emmanuelle: The Joys of a Woman (1975),84,56,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Sylvia KristelEmmanuelle Umberto OrsiniJe...
1964,Peter Pan (1953),77,72,0,0,0,0,0,0,0,...,1,0,0,1,1,0,1,0,0,Bobby DriscollPeter Pan (voice) Kathryn B...
1965,Casper (1995),100,63,0,0,0,0,0,0,0,...,1,0,1,1,0,0,0,0,0,Malachi PearsonCasper (voice) Christina R...
1966,Licence to Kill (1989),133,64,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,1,Timothy DaltonJames Bond Carey LowellPam ...

In [64]:
# reordering the dataframe 

df = df.iloc[:, [0, 1, 2, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3]]
df

,Movie Name,Time,Rating,Top Cast,Action,Science Fiction,Adventure,Thriller,Animation,Family,...,Mystery,Drama,Romance,Horror,History,War,TV Movie,Music,Documentary,Western
0,Venom: The Last Dance (2024),109,68,Tom HardyEddie Brock / Venom Chiwetel Eji...,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Moana 2 (2024),100,70,Auliʻi CravalhoMoana (voice) Dwayne Johns...,0,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,Elevation (2024),91,63,Anthony MackieWill Morena BaccarinNina ...,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Absolution (2024),112,59,Liam NeesonThug Ron PerlmanCharlie Conner...,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Red One (2024),124,70,Dwayne JohnsonCallum Drift Chris EvansJac...,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Killer Heat (2024),97,58,Richard MaddenLeonides / Elias Vardakis J...,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
1963,Emmanuelle: The Joys of a Woman (1975),84,56,Sylvia KristelEmmanuelle Umberto OrsiniJe...,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
1964,Peter Pan (1953),77,72,Bobby DriscollPeter Pan (voice) Kathryn B...,0,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1965,Casper (1995),100,63,Malachi PearsonCasper (voice) Christina R...,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1966,Licence to Kill (1989),133,64,Timothy DaltonJames Bond Carey LowellPam ...,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [65]:
print('df shape:', df.shape)
print('df columns:', df.columns)

# Saving df in csv file 

df.to_csv("full-cleaned-movies-2k.csv", index=False)

df shape: (1967, 23)
df columns: Index(['Movie Name', 'Time', 'Rating', 'Top Cast', 'Action', 'Science Fiction',
       'Adventure', 'Thriller', 'Animation', 'Family', 'Comedy', 'Crime',
       'Fantasy', 'Mystery', 'Drama', 'Romance', 'Horror', 'History', 'War',
       'TV Movie', 'Music', 'Documentary', 'Western'],
      dtype='object')

In [66]:
# Load your dataset
df_top_cast = pd.read_csv("cleaned_top_cast-2k.csv") 

# Extract only the 'Top Cast' column into a new DataFrame
top_cast_df = df_top_cast[['Top Cast']].copy()

In [67]:
# Function to get up to 7 cast members separated by ';'
def get_top_seven_cast(cast):
    # split by multiple spaces
    cast_list = re.split(r'\s{2,}', cast)
    cast = cast.strip()
    # Take only the first 7 names
    return "; ".join(cast_list[:7])

In [68]:
# Apply the function to the 'Top Cast' column
top_cast_df['Top 7 Cast'] = top_cast_df['Top Cast'].apply(get_top_seven_cast)

# Save to a new dataset or view
top_cast_df = top_cast_df[['Top 7 Cast']]
print(top_cast_df)  # Display the first few rows
top_cast_df.to_csv("top_seven_cast-2k.csv", index=False)

                                             Top 7 Cast
0     Tom HardyEddie Brock / Venom; Chiwetel Ejiofor...
1     Auliʻi CravalhoMoana (voice); Dwayne JohnsonMa...
2     Anthony MackieWill; Morena BaccarinNina; Maddi...
3     Liam NeesonThug; Ron PerlmanCharlie Conner; Yo...
4     Dwayne JohnsonCallum Drift; Chris EvansJack O'...
...                                                 ...
1962  Richard MaddenLeonides / Elias Vardakis; Josep...
1963  Sylvia KristelEmmanuelle; Umberto OrsiniJean; ...
1964  Bobby DriscollPeter Pan (voice); Kathryn Beaum...
1965  Malachi PearsonCasper (voice); Christina Ricci...
1966  Timothy DaltonJames Bond; Carey LowellPam Bouv...

[1967 rows x 1 columns]

In [69]:
df = df.drop(columns=['Top Cast'])
df = pd.concat([df, top_cast_df], axis=1)
df

,Movie Name,Time,Rating,Action,Science Fiction,Adventure,Thriller,Animation,Family,Comedy,...,Drama,Romance,Horror,History,War,TV Movie,Music,Documentary,Western,Top 7 Cast
0,Venom: The Last Dance (2024),109,68,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Tom HardyEddie Brock / Venom; Chiwetel Ejiofor...
1,Moana 2 (2024),100,70,0,0,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,Auliʻi CravalhoMoana (voice); Dwayne JohnsonMa...
2,Elevation (2024),91,63,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Anthony MackieWill; Morena BaccarinNina; Maddi...
3,Absolution (2024),112,59,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Liam NeesonThug; Ron PerlmanCharlie Conner; Yo...
4,Red One (2024),124,70,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,Dwayne JohnsonCallum Drift; Chris EvansJack O'...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Killer Heat (2024),97,58,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Richard MaddenLeonides / Elias Vardakis; Josep...
1963,Emmanuelle: The Joys of a Woman (1975),84,56,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Sylvia KristelEmmanuelle; Umberto OrsiniJean; ...
1964,Peter Pan (1953),77,72,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,Bobby DriscollPeter Pan (voice); Kathryn Beaum...
1965,Casper (1995),100,63,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,Malachi PearsonCasper (voice); Christina Ricci...
1966,Licence to Kill (1989),133,64,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,Timothy DaltonJames Bond; Carey LowellPam Bouv...

In [70]:
df = df.iloc[:, [0, 1, 2, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3]]
df

,Movie Name,Time,Rating,Top 7 Cast,Western,Documentary,Music,TV Movie,War,History,...,Mystery,Fantasy,Crime,Comedy,Family,Animation,Thriller,Adventure,Science Fiction,Action
0,Venom: The Last Dance (2024),109,68,Tom HardyEddie Brock / Venom; Chiwetel Ejiofor...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
1,Moana 2 (2024),100,70,Auliʻi CravalhoMoana (voice); Dwayne JohnsonMa...,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
2,Elevation (2024),91,63,Anthony MackieWill; Morena BaccarinNina; Maddi...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1
3,Absolution (2024),112,59,Liam NeesonThug; Ron PerlmanCharlie Conner; Yo...,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,1
4,Red One (2024),124,70,Dwayne JohnsonCallum Drift; Chris EvansJack O'...,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Killer Heat (2024),97,58,Richard MaddenLeonides / Elias Vardakis; Josep...,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1963,Emmanuelle: The Joys of a Woman (1975),84,56,Sylvia KristelEmmanuelle; Umberto OrsiniJean; ...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1964,Peter Pan (1953),77,72,Bobby DriscollPeter Pan (voice); Kathryn Beaum...,0,0,0,0,0,0,...,0,1,0,0,1,1,0,1,0,0
1965,Casper (1995),100,63,Malachi PearsonCasper (voice); Christina Ricci...,0,0,0,0,0,0,...,0,1,0,1,1,0,0,0,0,0
1966,Licence to Kill (1989),133,64,Timothy DaltonJames Bond; Carey LowellPam Bouv...,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1

In [71]:
print('df shape:', df.shape)
print('df columns:', df.columns)

# Saving df in csv file 

df.to_csv("full-cleaned-movies-7-top-cast-2k.csv", index=False)

df shape: (1967, 23)
df columns: Index(['Movie Name', 'Time', 'Rating', 'Top 7 Cast', 'Western', 'Documentary',
       'Music', 'TV Movie', 'War', 'History', 'Horror', 'Romance', 'Drama',
       'Mystery', 'Fantasy', 'Crime', 'Comedy', 'Family', 'Animation',
       'Thriller', 'Adventure', 'Science Fiction', 'Action'],
      dtype='object')